title: Aike de Jongste
email: info@aikedejongste.nl
description: >- # this means to ignore newlines until "baseurl:"
  Startups, programming, servers, travel and cars, I love them.
baseurl: "/amp"
url: "aikedejongste.github.io"
twitter_username: aikedejongste
github_username:  aikedejongste

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

destination:   _site/amp
layouts_dir:   ./_layouts-amp

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "default"

# exclude:
#   - Gemfile
